### ISSUE TITLE
Data files are not longer available

### ISSUE THREAD

**Issue by marinbenc** [Haolin-Yuan/EdgeMixup#1]
Hello,

First of all, thank you for your paper, it is an important and interesting contribution!

I tried to download the data for my own research, but the files have been deleted. Can you verify whether you are no longer sharing the data or if this is some mistake?

Thank you,
Marin

**Comment by hyuan4** [comment]
Hi Marin,

Thank you for being interested in our work. It seems that both links have expired. Can you leave your email address so that I can share you another link to download the dataset?

Best,
Haolin

**Comment by marinbenc** [comment]
Hello Haolin,

My email is marin.bencevic@ferit.hr. If possible, please also include the link for the segmentation dataset. Again, thank you for collecting and publishing the dataset!

All the best,
Marin
