### ISSUE TITLE
we need dataset

### ISSUE THREAD

**Issue by AlfredChung** [Haolin-Yuan/EdgeMixup#2]
Dear Yuan:
        Can you share the dataset again? The dataset is gone . Thank you !

**Comment by hyuan4** [comment]
Sorry about that. The new download link is: https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/hyuan4_jh_edu/EVT1V7xYvShMop8xIESavqYB7TQT34SMnbJpM5iGGpHD2w?e=rLdpfJ   Please let me know if you have any other questions.

**Comment by garlicman-man** [comment]
hey, will you release the segmentation dataset?

**Comment by hyuan4** [comment]
> hey, will you release the segmentation dataset?

Yes the download link for segmentation dataset is https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/hyuan4_jh_edu/Ec85EA4qeqhJvdVobVr42P4BcTe4kwA8MHVfucspc9BAww?e=23lO4f
