### ISSUE TITLE
Clarification regarding dataset source

### ISSUE THREAD

**Issue by Tianananana** [Haolin-Yuan/EdgeMixup#3]
Hello, thanks for your great work! I have a query regarding the dataset information. You mentioned in your paper that the skin images were collected from publicly available sources or from clinicians. May I ask for those collected from open source datasets, which datasets did you collect from? Thank you!

**Comment by hyuan4** [comment]
Thank you for your interest in our work. Yes, all public images are scraped from the internet.

**Comment by Tianananana** [comment]
ok, thank you!
